ContactDetails/Models/ContactDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Assignment3Test.Areas.ContactDetails.Models
{
    public class ContactDetails
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Address HomeAddress { get; set; }
        public Phone HomePhone { get; set; }
        public Phone CellPhone { get; set; }
    }

    public class Phone
    {
        public string CountryCode { get; set; }
        public string AreaCode { get; set; }
        public string PhoneNumber { get; set; }
    }

    public class Address
    {
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
    }
}

ContactDetails/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Assignment3Test.Areas.ContactDetails.Models;

namespace Assignment3Test.Areas.ContactDetails.Controllers
{
    public class ManagementController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }        

        [HttpPost]
        public ActionResult Index(Assignment3Test.Areas.ContactDetails.Models.ContactDetails details)
        {
            return View(details);
        }     
    }
}

ContactDetails/Views/Management/Index.cshtml
@model Assignment3Test.Areas.ContactDetails.Models.ContactDetails

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("Index", "Management"))
{
    <label>First Name</label>
    @Html.EditorFor(m => m.FirstName)
    <label>Last Name</label>
    @Html.EditorFor(m => m.LastName)
    <label>Email</label>
    @Html.EditorFor(m => m.Email)

    <h3>Cell Phone Details</h3>

    <label>Country Code</label>
    @Html.EditorFor(m => m.CellPhone.CountryCode)
    <label>Area Code</label>
    @Html.EditorFor(m => m.CellPhone.AreaCode)
    <label>Cell Number</label>
    @Html.EditorFor(m => m.CellPhone.PhoneNumber)

    <h3>Home Phone Details</h3>

    <label>Country Code</label>
    @Html.EditorFor(m => m.HomePhone.CountryCode)
    <label>Area Code</label>
    @Html.EditorFor(m => m.HomePhone.AreaCode)
    <label>Phone Number</label>
    @Html.EditorFor(m => m.HomePhone.PhoneNumber)

    <h3>Home Address Details</h3>

    <label>Country</label>
    @Html.EditorFor(m => m.HomeAddress.Country)
    <label>Province</label>
    @Html.EditorFor(m => m.HomeAddress.Province)
    <label>City</label>
    @Html.EditorFor(m => m.HomeAddress.City)
    <label>Address 1</label>
    @Html.EditorFor(m => m.HomeAddress.Line1)
    <label>Address 2</label>
    @Html.EditorFor(m => m.HomeAddress.Line2)
    <label>Address 3</label>
    @Html.EditorFor(m => m.HomeAddress.Line3)
    <label>Postal Code</label>
    @Html.EditorFor(m => m.HomeAddress.PostalCode)

    <br/>


    <input type="submit" value="Submit" />
}
@*<form method="POST" action="@Url.Action("Index", "Management")">
   @ViewBag. 
    <input type="submit"/>
</form>*@

<br/>
<a>Back To List</a>

ContactDetails/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>